# Generated by Django 4.1 on 2023-08-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0011_delete_espaciotrabajo'),
        ('persona', '0004_alter_persona_cuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('esAlimento', models.BooleanField(default=False)),
                ('esRopa', models.BooleanField(default=False)),
                ('esMaterial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Entrega')),
                ('referencia', models.CharField(max_length=100)),
                ('esComprado', models.BooleanField(default=False, verbose_name='Es Comprado')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Procesada')], default='P', max_length=1, verbose_name='Estado')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_rec_alm_gr', to='persona.grupo')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_rec_alm_inst', to='parametros.institucion')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_rec_alm_per', to='persona.persona')),
            ],
            options={
                'verbose_name_plural': 'Recepcion de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Entrega')),
                ('referencia', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Procesada')], default='P', max_length=1, verbose_name='Estado')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_alm_gr', to='persona.grupo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_alm_per', to='persona.persona')),
            ],
            options={
                'verbose_name_plural': 'Entregas de Artículos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_rec_art', to='almacen.articulo')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_rec', to='almacen.recepcion')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Recepcion de Artículos',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_ent_art', to='almacen.articulo')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_ent', to='almacen.entrega')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Entregas de Artículos',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipoArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.tipoarticulo'),
        ),
    ]
