# Generated by Django 4.1 on 2023-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
