# Generated by Django 4.1 on 2022-10-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_institucion'),
        ('generos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'app__nombre': 'Géneros'}, on_delete=django.db.models.deletion.CASCADE, related_name='gti', to='parametros.tipointervecion'),
        ),
    ]
