# Generated by Django 3.2 on 2022-04-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipointervecion',
            name='lugar',
        ),
    ]
