# Generated by Django 3.2 on 2022-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_remove_tipointervecion_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autopercepcion',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='identificacolores',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='testvistacerca',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='testvistalejos',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='venumerosletras',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
