# Generated by Django 3.2 on 2022-05-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0004_auto_20220501_1120'),
        ('parametros', '0005_medicamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autopercepcion',
        ),
        migrations.DeleteModel(
            name='Cobertura',
        ),
        migrations.DeleteModel(
            name='Dificultad',
        ),
        migrations.DeleteModel(
            name='ElementoCuidado',
        ),
        migrations.DeleteModel(
            name='Enfermedad',
        ),
        migrations.DeleteModel(
            name='IdentificaColores',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='PresionArterial',
        ),
        migrations.DeleteModel(
            name='ProblematicaBarrio',
        ),
        migrations.DeleteModel(
            name='TestVistaCerca',
        ),
        migrations.DeleteModel(
            name='TestVistaLejos',
        ),
        migrations.DeleteModel(
            name='VeNumerosLetras',
        ),
    ]
