# Generated by Django 4.1 on 2022-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0006_auto_20220501_1120"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
            options={"verbose_name_plural": "Instituciones",},
        ),
    ]
