# Generated by Django 4.1 on 2023-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_institucion_escentroformacion_institucion_escuidados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Espacios de Trabajo',
            },
        ),
    ]
