# Generated by Django 4.1 on 2023-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_remove_reserva_espacio_reserva_solicitantes'),
        ('parametros', '0010_espaciotrabajo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EspacioTrabajo',
        ),
    ]
