# Generated by Django 3.2 on 2022-05-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0006_auto_20220501_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('local', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ramas',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('piso_dpto', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=20)),
                ('inicio_actividades', models.DateField(blank=True)),
                ('registro', models.CharField(blank=True, max_length=20)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.localidad')),
            ],
            options={
                'verbose_name_plural': 'Unidades Productivas',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_trabajo.dependencia')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_trabajo.rama')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
