# Generated by Django 3.2 on 2022-04-27 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0004_localidad_nacionalidad'),
        ('persona', '0002_auto_20220426_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('local', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ramas',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Trabajos',
            },
        ),
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('piso_dpto', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=20)),
                ('inicio_actividades', models.DateField(blank=True)),
                ('registro', models.CharField(blank=True, max_length=20)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.localidad')),
            ],
            options={
                'verbose_name_plural': 'Unidades Productivas',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.dependencia')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField()),
                ('estado_programa', models.CharField(choices=[('a', 'Activo'), ('i', 'Inactivo')], max_length=10)),
                ('estado_persona', models.CharField(choices=[('t', 'Trabaja'), ('n', 'No Trabaja')], max_length=10)),
                ('solicitud', models.DateField(blank=True, default=datetime.datetime.now)),
                ('ingreso', models.DateField(default=datetime.datetime.now)),
                ('notas', models.TextField(blank=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfp', to='persona.persona')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.programa')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.trabajo')),
                ('unidad_productiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.unidadproductiva')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='rama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.rama'),
        ),
    ]
