# Generated by Django 3.2 on 2022-04-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_localidad_nacionalidad'),
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'verbose_name_plural': 'Fichas'},
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.ficha')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tti', to='parametros.tipointervecion')),
            ],
            options={
                'verbose_name_plural': 'Intervenciones',
            },
        ),
    ]
