# Generated by Django 3.2 on 2022-05-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0002_auto_20220427_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='solicitud',
        ),
        migrations.CreateModel(
            name='Lista_Espera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ale', to='trabajo.actividad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajo.ficha')),
            ],
            options={
                'verbose_name_plural': 'Lista de Espera',
            },
        ),
    ]
