# Generated by Django 3.2 on 2022-05-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20220426_2304'),
        ('trabajo', '0003_auto_20220501_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista_espera',
            old_name='Actividad',
            new_name='actividad',
        ),
        migrations.AlterField(
            model_name='lista_espera',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
