# Generated by Django 4.1 on 2022-09-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parametros", "0007_institucion"),
        ("trabajo", "0005_auto_20220501_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervencion",
            name="institucion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ttin",
                to="parametros.institucion",
            ),
            preserve_default=False,
        ),
    ]
