# Generated by Django 4.1 on 2022-10-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_institucion'),
        ('trabajo', '0006_intervencion_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resumen', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'app__nombre': 'Trabajo'}, on_delete=django.db.models.deletion.CASCADE, related_name='tti', to='parametros.tipointervecion'),
        ),
    ]
