# Generated by Django 4.1 on 2022-10-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_etiqueta'),
        ('trabajo', '0007_nota_alter_intervencion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='net', to='parametros.etiqueta'),
        ),
    ]
