# Generated by Django 4.1 on 2023-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0008_nota_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nexo',
            field=models.BooleanField(default=False),
        ),
    ]
