# Generated by Django 3.2 on 2022-04-26 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_localidad_nacionalidad'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='persona',
            name='cp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='cuit',
            field=models.CharField(default=1, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametros.localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametros.nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='piso_dpto',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ingreso',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
