# Generated by Django 4.1 on 2023-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_persona_cp_alter_persona_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
