# Generated by Django 4.1 on 2023-06-06 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0009_institucion_escentroformacion_institucion_escuidados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('direccion', models.CharField(max_length=100)),
                ('manzanaRENABAP', models.CharField(blank=True, max_length=10, null=True)),
                ('loteRENABAP', models.CharField(blank=True, max_length=10, null=True)),
                ('encuestadore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
            ],
            options={
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Parentezcos',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('dniArgentino', models.BooleanField()),
                ('concurreEscuela', models.BooleanField()),
                ('tieneDiscapacidad', models.BooleanField()),
                ('tieneCertificadoDiscapacidad', models.BooleanField()),
                ('leeEscribe', models.BooleanField()),
                ('centroFormacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstForm', to='parametros.institucion')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.encuesta')),
                ('establecimientoCuidados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstCuida', to='parametros.institucion')),
                ('establecimientoEducativo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstEduc', to='parametros.institucion')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.genero')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.nacionalidad')),
                ('parentezco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.parentezco')),
            ],
            options={
                'verbose_name_plural': 'Familiares',
            },
        ),
    ]
