# Generated by Django 4.1 on 2023-06-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_institucion_escentroformacion_institucion_escuidados_and_more'),
        ('censo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialesPared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Materiales de Paredes',
            },
        ),
        migrations.CreateModel(
            name='MaterialesPiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Materiales de Pisos',
            },
        ),
        migrations.CreateModel(
            name='MaterialesTecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Materiales de Techos',
            },
        ),
        migrations.CreateModel(
            name='OpcionesAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Servicio de Agua Potable',
            },
        ),
        migrations.CreateModel(
            name='OpcionesCloacas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Servicio de Cloacas',
            },
        ),
        migrations.CreateModel(
            name='OpcionesGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Servicio de Gas',
            },
        ),
        migrations.CreateModel(
            name='OpcionesLuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Servicio de Luz',
            },
        ),
        migrations.CreateModel(
            name='OpcionesResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Servicio de Recolección de Residuos',
            },
        ),
        migrations.CreateModel(
            name='TipoBanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Baño',
            },
        ),
        migrations.CreateModel(
            name='TipoInodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Inodoros',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Trabajos',
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Viviendas',
            },
        ),
        migrations.CreateModel(
            name='UsoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Usos de la Vivienda',
            },
        ),
        migrations.AlterModelOptions(
            name='encuesta',
            options={'verbose_name_plural': '1-Encuestas'},
        ),
        migrations.AlterModelOptions(
            name='familia',
            options={'verbose_name_plural': '2-Familiares'},
        ),
        migrations.AlterField(
            model_name='familia',
            name='centroFormacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstForm', to='parametros.institucion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='establecimientoCuidados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstCuida', to='parametros.institucion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='establecimientoEducativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstEduc', to='parametros.institucion'),
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHabitantes', models.IntegerField()),
                ('habitacionesPernocte', models.IntegerField()),
                ('tiempoHabita', models.IntegerField()),
                ('tieneCertificado', models.BooleanField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.encuesta')),
                ('materialesPared', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoPared', to='censo.materialespared')),
                ('materialesPiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoPiso', to='censo.materialespiso')),
                ('materialesTecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoTecho', to='censo.materialestecho')),
                ('tipoBanio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoBa', to='censo.tipobanio')),
                ('tipoInodoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoIn', to='censo.tipoinodoro', verbose_name='Tipo de Baño')),
                ('tipoVivienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipo', to='censo.tipovivienda')),
                ('usoVivienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivUso', to='censo.usovivienda')),
            ],
            options={
                'verbose_name_plural': '4-Situación vivienda',
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieneTrabajo', models.BooleanField()),
                ('aportaJubilación', models.BooleanField()),
                ('jubiladxPensionadx', models.BooleanField()),
                ('percibeAsignaciones', models.BooleanField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.encuesta')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.familia')),
                ('tipoTrabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traTipo', to='censo.tipotrabajo')),
            ],
            options={
                'verbose_name_plural': '3-Situación laboral',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortesFataPago', models.BooleanField()),
                ('tarifaSocial', models.BooleanField()),
                ('agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoPiso', to='censo.opcionesagua')),
                ('cloacas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoTecho', to='censo.opcionescloacas')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censo.encuesta')),
                ('gas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipoPared', to='censo.opcionesgas')),
                ('luz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivTipo', to='censo.opcionesluz')),
                ('recoleccionResiduos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivResid', to='censo.opcionesresiduos')),
            ],
            options={
                'verbose_name_plural': '5-Servicios Públicos',
            },
        ),
    ]
