# Generated by Django 4.1 on 2023-06-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0003_espaciospoderosa_infrasocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosEspeciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ingresos Especiales',
            },
        ),
        migrations.AddField(
            model_name='trabajo',
            name='frecuenciaCobroTrabajo',
            field=models.CharField(blank=True, choices=[('D', 'Diaria'), ('S', 'Semanal'), ('Q', 'Quincenal'), ('M', 'Mensual')], default='1', max_length=1, null=True, verbose_name='Frecuencia de ingresos por trabajo'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='percibeAcompaniar',
            field=models.BooleanField(default=True, verbose_name='Percibe Acompañar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='percibeAsignaciones',
            field=models.BooleanField(verbose_name='Percibe Asignaciones Familiares'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='percibeOtros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='censo.ingresosespeciales', verbose_name='Percibe otros ingresos'),
        ),
    ]
