# Generated by Django 4.1 on 2023-06-26 11:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0009_institucion_escentroformacion_institucion_escuidados_and_more'),
        ('censo', '0004_ingresosespeciales_trabajo_frecuenciacobrotrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='centroFormacion',
            field=models.ForeignKey(blank=True, limit_choices_to={'esCentroFormacion': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstForm', to='parametros.institucion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='establecimientoCuidados',
            field=models.ForeignKey(blank=True, limit_choices_to={'esCuidados': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstCuida', to='parametros.institucion'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='establecimientoEducativo',
            field=models.ForeignKey(blank=True, limit_choices_to={'esEducativa': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famEstEduc', to='parametros.institucion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='familia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='encuesta', chained_model_field='encuesta', on_delete=django.db.models.deletion.CASCADE, to='censo.familia'),
        ),
    ]
