# Generated by Django 4.0.4 on 2022-04-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0002_aplicacion_genero_sexo_alter_ciudad_options_and_more'),
        ('persona', '0002_remove_persona_llave_persona_grupo_persona_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.genero')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.sexo')),
            ],
            options={
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.ficha')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipointervecion')),
            ],
            options={
                'verbose_name_plural': 'Intervenciones',
            },
        ),
    ]
