# Generated by Django 3.2 on 2022-04-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_auto_20220426_2304'),
        ('parametros', '0004_localidad_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateField()),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.cobertura')),
                ('dificultades', models.ManyToManyField(related_name='dif', to='parametros.Dificultad')),
                ('enfermedades', models.ManyToManyField(related_name='enf', to='parametros.Enfermedad')),
                ('enfermedades_cronicas', models.ManyToManyField(related_name='enf_cronicas', to='parametros.Enfermedad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.genero')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfp', to='persona.persona')),
            ],
            options={
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.ficha')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipointervecion')),
            ],
            options={
                'verbose_name_plural': 'Intervenciones',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('autopercepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.autopercepcion')),
                ('identifica_colores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.identificacolores')),
                ('identifica_letras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.venumerosletras')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.ficha')),
                ('presion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.presionarterial')),
                ('test_cerca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.testvistacerca')),
                ('test_lejos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.testvistalejos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipointervecion')),
            ],
            options={
                'verbose_name_plural': 'Atenciones',
            },
        ),
    ]
