# Generated by Django 3.2 on 2022-04-27 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_localidad_nacionalidad'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sti', to='parametros.tipointervecion'),
        ),
    ]
