# Generated by Django 3.2 on 2022-05-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_medicamento'),
        ('salud', '0002_alter_intervencion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField()),
                ('detalle', models.TextField()),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.atencion')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.medicamento')),
            ],
            options={
                'verbose_name_plural': 'Medicamentos Entregados/Recetados',
            },
        ),
    ]
