# Generated by Django 3.2 on 2022-05-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_salud', '0001_initial'),
        ('salud', '0003_lista_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='autopercepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.autopercepcion'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='identifica_colores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.identificacolores'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='identifica_letras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.venumerosletras'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='presion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.presionarterial'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='test_cerca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.testvistacerca'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='test_lejos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.testvistalejos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.cobertura'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='dificultades',
            field=models.ManyToManyField(related_name='dif', to='parametros_salud.Dificultad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades',
            field=models.ManyToManyField(related_name='enf', to='parametros_salud.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades_cronicas',
            field=models.ManyToManyField(related_name='enf_cronicas', to='parametros_salud.Enfermedad'),
        ),
        migrations.AlterField(
            model_name='lista_medicamentos',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.medicamento'),
        ),
    ]
