# Generated by Django 3.2 on 2022-05-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20220426_2304'),
        ('parametros', '0006_auto_20220501_1120'),
        ('salud', '0004_auto_20220501_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atpe', to='persona.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atti', to='parametros.tipointervecion')),
            ],
            options={
                'verbose_name_plural': 'Agenda de turnos',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('sobreturno', models.BooleanField()),
                ('detalle', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.agendaturnos')),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salud.atencion')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atfi', to='salud.ficha')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
