# Generated by Django 3.2 on 2022-05-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_salud', '0002_enfermedadcronica'),
        ('salud', '0005_agendaturnos_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades_cronicas',
            field=models.ManyToManyField(related_name='enf_cronicas', to='parametros_salud.EnfermedadCronica'),
        ),
    ]
