# Generated by Django 3.2 on 2022-05-04 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_salud', '0003_materialvivienda_serviciovivienda_situacionvivienda'),
        ('salud', '0011_auto_20220502_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='materiales_vivienda',
            field=models.ManyToManyField(blank=True, null=True, to='parametros_salud.MaterialVivienda'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='servicios_vivienda',
            field=models.ManyToManyField(blank=True, null=True, to='parametros_salud.ServicioVivienda'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='situacion_vivienda',
            field=models.ManyToManyField(blank=True, null=True, to='parametros_salud.SituacionVivienda'),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(22, 54, 57, 847718)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(22, 54, 57, 847746)),
        ),
    ]
