# Generated by Django 3.2 on 2022-05-04 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salud', '0012_auto_20220504_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='ambientes_vivienda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='convivientes_vivienda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='hijes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(22, 59, 0, 409090)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(22, 59, 0, 409119)),
        ),
    ]
