# Generated by Django 4.1 on 2022-09-05 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salud", "0014_intervencion_institucion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaturnos",
            name="hora_desde",
            field=models.TimeField(default=datetime.time(3, 17, 42, 257189)),
        ),
        migrations.AlterField(
            model_name="agendaturnos",
            name="hora_hasta",
            field=models.TimeField(default=datetime.time(3, 17, 42, 257211)),
        ),
    ]
