# Generated by Django 4.1 on 2022-10-06 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0007_institucion'),
        ('salud', '0017_alter_agendaturnos_hora_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(18, 36, 34, 602432)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(18, 36, 34, 602449)),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'app__nombre': 'Salud'}, on_delete=django.db.models.deletion.CASCADE, related_name='sti', to='parametros.tipointervecion'),
        ),
    ]
