# Generated by Django 4.1 on 2023-04-19 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros_salud', '0003_materialvivienda_serviciovivienda_situacionvivienda'),
        ('salud', '0020_alter_agendaturnos_hora_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nro_afiliade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(23, 31, 56, 816816)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(23, 31, 56, 816831)),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='dificultades',
            field=models.ManyToManyField(related_name='dif', to='parametros_salud.dificultad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades',
            field=models.ManyToManyField(related_name='enf', to='parametros_salud.enfermedad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades_cronicas',
            field=models.ManyToManyField(related_name='enf_cronicas', to='parametros_salud.enfermedadcronica'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='materiales_vivienda',
            field=models.ManyToManyField(to='parametros_salud.materialvivienda'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='servicios_vivienda',
            field=models.ManyToManyField(to='parametros_salud.serviciovivienda'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='situacion_vivienda',
            field=models.ManyToManyField(to='parametros_salud.situacionvivienda'),
        ),
    ]
