# Generated by Django 4.1 on 2023-04-19 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_etiqueta'),
        ('parametros_salud', '0004_especialidad'),
        ('salud', '0021_ficha_nro_afiliade_alter_agendaturnos_hora_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(23, 47, 24, 264940)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(23, 47, 24, 264954)),
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=8, unique=True)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('piso_dpto', models.CharField(blank=True, max_length=20, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.ManyToManyField(related_name='esmed', to='parametros_salud.especialidad')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.localidad')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='medicos',
            field=models.ManyToManyField(related_name='medcab', to='salud.profesional'),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atpe', to='salud.profesional'),
        ),
    ]
