# Generated by Django 4.1 on 2023-04-19 03:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0008_etiqueta'),
        ('parametros_salud', '0004_especialidad'),
        ('salud', '0022_turno_asistio_alter_agendaturnos_hora_desde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='enfermedades',
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_desde',
            field=models.TimeField(default=datetime.time(0, 10, 43, 113575)),
        ),
        migrations.AlterField(
            model_name='agendaturnos',
            name='hora_hasta',
            field=models.TimeField(default=datetime.time(0, 10, 43, 113589)),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='dificultades',
            field=models.ManyToManyField(blank=True, related_name='dif', to='parametros_salud.dificultad'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='enfermedades_cronicas',
            field=models.ManyToManyField(blank=True, related_name='enf_cronicas', to='parametros_salud.enfermedadcronica'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='materiales_vivienda',
            field=models.ManyToManyField(blank=True, to='parametros_salud.materialvivienda'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='medicos',
            field=models.ManyToManyField(blank=True, related_name='medcab', to='salud.profesional'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='servicios_vivienda',
            field=models.ManyToManyField(blank=True, to='parametros_salud.serviciovivienda'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='situacion_vivienda',
            field=models.ManyToManyField(blank=True, to='parametros_salud.situacionvivienda'),
        ),
        migrations.CreateModel(
            name='Turno_Externos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asistio', models.BooleanField(blank=True, null=True)),
                ('demanda_insatisfecha', models.BooleanField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('centro_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.institucion')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros_salud.especialidad')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiturex', to='salud.ficha')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salud.profesional')),
            ],
            options={
                'verbose_name_plural': 'Turnos Externos',
            },
        ),
    ]
