# Generated by Django 4.1 on 2023-08-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_cuit'),
        ('organizacion', '0002_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='espacio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='solicitantes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.grupo'),
            preserve_default=False,
        ),
    ]
