# Generated by Django 4.1 on 2023-08-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0011_delete_espaciotrabajo'),
        ('persona', '0004_alter_persona_cuit'),
        ('organizacion', '0004_tipotarea_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.grupo'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='relaciones',
            field=models.ManyToManyField(to='parametros.institucion'),
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='responsable',
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
