# Generated by Django 4.1 on 2023-08-17 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_cuit'),
        ('organizacion', '0005_tarea_grupo_alter_tarea_relaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resumen', models.TextField(max_length=100)),
                ('detalle', models.TextField()),
                ('esAsamblea', models.BooleanField(default=True, verbose_name='Nota de Asamblea')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.grupo')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.tarea')),
            ],
            options={
                'verbose_name_plural': 'Notas de Reuniones',
            },
        ),
    ]
