# Generated by Django 4.1 on 2023-08-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_notareunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notareunion',
            name='resumen',
            field=models.CharField(max_length=100),
        ),
    ]
